# Generated by Django 3.2.24 on 2024-03-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_postcategoryeducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategoryeducation',
            name='academic_performance',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postcategoryeducation',
            name='current_school',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postcategoryeducation',
            name='grade',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postcategoryeducation',
            name='reason_for_application',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
