# Generated by Django 3.2.24 on 2024-03-30 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0003_auto_20240330_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategoryHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('medical_history', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('allergies', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('height', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('blood', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('health_insurance', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('govt_health_card', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('submit_date', models.DateField(blank=True, default=None, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.welfarepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
