# Generated by Django 3.2.24 on 2024-04-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_auto_20240330_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategoryeducation',
            name='new_flag',
            field=models.BooleanField(default=True),
        ),
    ]
