# Generated by Django 3.2.24 on 2024-04-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_postcategoryeducation_new_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategoryhealth',
            name='new_flag',
            field=models.BooleanField(default=True),
        ),
    ]
