# Generated by Django 3.2.24 on 2024-04-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_askquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='askquery',
            name='query',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
