# Generated by Django 3.2.24 on 2024-04-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_askquery_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AskQuery',
        ),
    ]
