# Generated by Django 3.2.24 on 2024-04-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_auto_20240412_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welfarepost',
            name='post_category',
            field=models.CharField(blank=True, choices=[('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Employment', 'Employment'), ('Social_Security', 'Social Security'), ('Housing', 'Housing'), ('Rural_Development', 'Rural Development'), ('Minority_Welfare', 'Minority Welfare')], default='', max_length=60, null=True),
        ),
    ]
