# Generated by Django 3.2.24 on 2024-03-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_customuser_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryEducation',
        ),
    ]
