# Generated by Django 3.2.24 on 2024-04-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_delete_categoryeducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('q_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('q_mobile', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('q_query', models.TextField(blank=True, default=None, max_length=255, null=True)),
                ('q_submit_date', models.DateField(blank=True, default=None, null=True)),
                ('q_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
