# Generated by Django 3.2.24 on 2024-04-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_askquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AskQuery',
        ),
    ]
