# Generated by Django 3.2.16 on 2024-05-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
